name: make-build
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  building-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build project
        run: cd trabalho-pratico ; make all

